### ISSUE TITLE
Add a view logs button

### ISSUE THREAD

**Issue by rymnc** [trufflesuite/truffle-teams#11]
![image](https://user-images.githubusercontent.com/43716372/85834542-3553cc00-b7b1-11ea-8d6e-baca6487e1e7.png)
Currently, one can view the log when one clicks the `#1 Passed` Button, but I think it would be neater, if there was a button to view logs,
right under the `restart build` Button

**Comment by mikeseese** [comment]
Thanks for the suggestion! I'll forward this along to the Product team

**Comment by rymnc** [comment]
any update?

**Comment by mikeseese** [comment]
Hey @aaryamannchallani; this has been worked and will be in our next release in the coming weeks
