### ISSUE TITLE
Builds are stuck in "In Progress"

### ISSUE THREAD

**Issue by mikeseese** [trufflesuite/truffle-teams#2]
@sbrichards reported an issue with his build stuck in "In Progress" without any build output. I'm making this issue for us to follow up on our findings as we look into it!

Thanks again @sbrichards for the report!

**Comment by samajammin** [comment]
Thank you Truffle team! 

To clarify, my first attempt on the build did not output anything. My second attempt (i.e. pushing up another commit) DID output but is left hanging in "In Progress" hours after kicking it off. Here's the output of that build if it's helpful:
https://gist.github.com/sbrichards/7081868000001ef914af960fd3d52e46

**Comment by mikeseese** [comment]
Much appreciated! Thanks for the clarification!

**Comment by samajammin** [comment]
@seesemichaelj any update on this? Thanks.

**Comment by mikeseese** [comment]
Hey @sbrichards! We attempted to fix the problem a couple of weeks after this, and again a week or so after that. We have been trying to fix some architectural bugs that hopefully this will go away soon. Thanks for your patience!

**Comment by mikeseese** [comment]
Hey @sbrichards, after some looking into this, we believe the next release (hopefully tomorrow) should solve this problem for you!

**Comment by mikeseese** [comment]
@sbrichards could you kick off another build (by just making a commit)? Thanks!

**Comment by samajammin** [comment]
It works! Feel free to close this out. Thanks.

**Comment by nicholasjpaterno** [comment]
Awesome! Thanks @sbrichards!
