### ISSUE TITLE
a

### ISSUE THREAD

**Issue by tppk** [trufflesuite/truffle-teams#5]
Compiling your contracts...
===========================
Error executing vyper:
/bin/sh: 1: vyper: not found

Truffle v5.0.10 (core: 5.0.10)
Node v11.13.0

**Comment by tppk** [comment]
[https://coincolors.co/wp-content/uploads/2018/05/btc-price-CoinColors.co_.jpg](url)

**Comment by nicholasjpaterno** [comment]
@tppk Please do not post masked links or I'll be forced to block your participation in this repository.

**Comment by seesemichaelj** [comment]
Duplicate of #4
