### ISSUE TITLE
Unable to turn on external CI option for private repository—unexpected permission error

### ISSUE THREAD

**Issue by waterlink** [trufflesuite/truffle-teams#8]
Hi there, thank you so much for your work on Truffle Teams! It’s a very promising tool!

In our context right now, we don’t want to use the Truffle Teams for CI (just yet), but instead only for Monitoring of our existing smart contracts. When I have provided some artifacts and smart contract addresses, I’ve seen that Truffle Teams internal CI service now automatically runs build on every commit.

Then I was trying to disable this by switching on the external CI option for this repository, and got the following problem:

<img width="804" alt="Screenshot 2020-05-26 at 18 22 38" src="https://user-images.githubusercontent.com/609046/82925681-5771e880-9f7e-11ea-996e-9cea23c393ff.png">

Which is a really strange error, because I have a write access to Github repository and I have a “manager” role in the Truffle Teams project:

<img width="312" alt="Screenshot 2020-05-26 at 18 22 45" src="https://user-images.githubusercontent.com/609046/82925734-6c4e7c00-9f7e-11ea-96ab-4555182e92a1.png">

Any thoughts what could be wrong?

**Comment by eshaben** [comment]
Hey @waterlink, thanks for creating this issue! I apologize for the delay in response and that you are running into problems. I did some initial testing and couldn't see any glaring issues with how we are handling permissions. I'm curious, are you still encountering this error?

**Comment by eshaben** [comment]
Hello again 👋 , after looking into this further we've discovered we do have a bug in our code. We'll release a fix soon! Thanks again for reporting the issue!

**Comment by mikeseese** [comment]
Reopening this until this fix has been released (it got auto closed when we merged into our develop branch)

Should be released in the next couple of days! Thanks again for reporting this

**Comment by waterlink** [comment]
Thank you for quick response and for finding the problem!

**Comment by mikeseese** [comment]
Hey @waterlink, I believe this should be fixed now! Feel free to reopen if you're still seeing the issue
